# Generated by Django 5.0.2 on 2024-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspace",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
