# Generated by Django 5.0.1 on 2024-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=100)),
                ("owner_phone", models.CharField(max_length=20)),
                ("street_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("slots", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("opening_hours", models.TimeField()),
                ("closing_hours", models.TimeField()),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="uploads/image/")),
                ("vehicle_wash_available", models.BooleanField(default=False)),
            ],
        ),
    ]
