# Generated by Django 5.0.2 on 2024-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_project", "0002_added_is_paid_field_in_parking_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
